### ISSUE TITLE
Code Polishing

### ISSUE THREAD

**Issue by jcfrei** [wtag/PIDAS-CORA-JAVA#41]
First of all, I believe we have made some very good progress on implementing the requested features. until friday we want to focus on polishing the code we currently have, since this has been specifically requested by PIDAS. here are some things to do:

reduce unused validators. the CoraValidator for example checks: cora.getName() != null && cora.getId() == null Why does it need to check if getId() == null? The is is auto-generated and should always be present if I'm not mistaken. Please remove redunancies like these in the Validator classes.

getId() in Cora also returns Long rather than long? Why is this? Wouldn't long work just as well? Same for Integer rather than int in Rule.

remove unused classes, like CoraLoaderTask

remove master and tenante packages and put all classes in one package.

why do Role and Company extend the BaseObject class? I think for readability we should remove the BaseObject class and implement the fields directly in Company and Role.

Commentaries: Classes where it isn't clear what they do: UserMenu, UserMenuData, CustomUserDetailsService, TenantIdentifierInterceptorAdapter

don' use separate package-info.java classes for master and tenant. just one in the parent package - that means:
remove package-info.java in package package com.pidas.cora.controller.master and  com.pidas.cora.controller.tenant and create one in com.pidas.cora.controller;

package-info in com.pidas.cora.config; needs the following info: what does each class do? 
DatabaseConfiguration: does it setup the database? create the connection? write this in the commentary. 
same for MultiTenancyJpaConfiguration and SecurityConfiguration. what do they do specifically?

I've created an example in package-info.java in the controller package. please also annotate the methods within this package.

Dependency Injection
Consistent dependency injection only via the constructor - I know this introduces more code but it was specifically requested.
So instead of:

@Autowired
UserRepository userRepository;

always create a constructor like:
ChangePasswordChangeFilter(UserRepository userRepository) {
	this.userRepository = userRepository;
}

then you can omit the @Autowired and @Inject annotations. Later on we will add null checks.

**Comment by amo-wtag** [comment]
1. Reduced unused validation >> Remove unused validations and comment out in custom validator class, why getId() check it required.
2. Remove BaseObject Model Class >> Done
3. Delete DataLoader Unused Class >> Done
4. Dependency Injection, remove @Autowired >> Done
5. Use of Long and Integer >> Keep it as it is, as it's recommended for Hibernate form validation
