### ISSUE TITLE
TODO 16/8/2017

### ISSUE THREAD

**Issue by jcfrei** [wtag/PIDAS-CORA-JAVA#47]
make sure all field have access modifiers: private, public, etc...

every class needs a description, add all descriptions together to the package-info.java

classes that need commentary
WebMvcConfig, CurrentTenantResolverImpl, ChangePasswordChangeFilter, TenantIdentifierInterceptorAdapter
LocalDateTimePersistenceConverter, MultitenantResource, UserMenu, UserMenuData

add Get, Post etc request mappings to Mappings.java in AssetController, ClientTaskController, CoraController, HomeController, RuleController, TenantController, UserController

save, save&new buttons are confusing on /userForm

email verification is incorret: bla@bla works

why dow we need to update the lockers in the cora with the lockers from lockerRepository inside saveLockerStatus? can't they reference the same Lockers?

use Optional isPresent()

**Comment by amo-wtag** [comment]
Till now we have modified below things:
1. Access Modifier >> Done
2. Commentary for mentioned class >> Done
3. Mapping.java >> Done
4. Email Validation >> Done
5. Save and Save&New button >> Its user requirement, so should we remove the Save&New button? 
6. Package-info.java >> Done
